<?php

return [
    'name' => 'Modeste Konlani',
    'first_name' => 'Modeste',
    'last_name' => 'Konlani',
    'role' => 'Développeur fullstack',
    'location' => 'Agoè-Zossimé, Lomé',
    'country' => 'Togo',
    'email' => 'konlanimodeste9177@gmail.com',
    'phone' => '+228 91 77 38 82',
    'phone_href' => '+22891773882',
    'github' => 'https://github.com/canis-lupu2006',
    'github_handle' => 'canis-lupu2006',
    'cv' => '/cv/CV-Modeste-Konlani.pdf',
    'tagline' => 'Des applications utilisées, pas seulement présentées.',
    'intro' => "Je conçois des outils pour des usages réels — gestion d'entreprise, cartographie d'urgence, analytics — du modèle de données jusqu'à ce que ça tourne.",
    'stats' => [
        ['value' => '8', 'suffix' => '', 'label' => 'projets livrés'],
        ['value' => '3', 'suffix' => '', 'label' => 'hackathons'],
        ['value' => '2', 'suffix' => '', 'label' => 'apps en prod'],
        ['value' => '48h', 'suffix' => '', 'label' => 'pour répondre', 'static' => true],
    ],
    'bio' => [
        "Je m'appelle Modeste Konlani. J'habite à Agoè-Zossimé, à Lomé, et je prépare une licence professionnelle Informatique, Réseaux et Télécoms à l'ESGIS-Togo.",
        "Je développe surtout des applications que quelqu'un ouvre le lendemain : factures et stock pour une entreprise de froid, carte collaborative des inondations de Lomé, dashboards, pipelines CI/CD.",
        "Côté technique, je suis à l'aise sur Java / Spring Boot et MySQL, et je construis aussi en React, Flutter et Laravel. Ce qui m'intéresse, c'est le produit de bout en bout.",
    ],
    'education' => [
        [
            'period' => '2024 — aujourd\'hui',
            'title' => 'Licence professionnelle IRT',
            'place' => 'ESGIS-Togo',
            'detail' => 'Informatique, Réseaux et Télécommunications',
        ],
        [
            'period' => '2023 — 2024',
            'title' => 'Baccalauréat, série D',
            'place' => 'Lycée Scientifique René Descartes',
            'detail' => 'Parcours scientifique',
        ],
        [
            'period' => '2022 — 2023',
            'title' => 'Baccalauréat 1re partie, série D',
            'place' => 'Lycée Scientifique René Descartes',
            'detail' => 'Parcours scientifique',
        ],
    ],
    'languages' => [
        ['name' => 'Moba', 'level' => 'Langue maternelle'],
        ['name' => 'Français', 'level' => 'Courant'],
        ['name' => 'Anglais', 'level' => 'Intermédiaire'],
    ],
    'skills' => [
        'Java', 'Spring Boot', 'MySQL', 'Laravel', 'React', 'Flutter', 'Jenkins', 'Maven', 'Git', 'MERISE / UML',
    ],
    'stack_groups' => [
        [
            'label' => 'Langages & frameworks',
            'items' => ['Java', 'Spring Boot', 'JDBC', 'Laravel', 'React', 'Flutter'],
        ],
        [
            'label' => 'Données',
            'items' => ['MySQL', 'Modélisation relationnelle', 'MERISE / UML'],
        ],
        [
            'label' => 'Outils',
            'items' => ['Jenkins', 'Maven', 'Git / GitHub', 'IntelliJ IDEA'],
        ],
    ],
    'projects' => [
        [
            'slug' => 'todzi',
            'title' => 'TODZI',
            'kicker' => 'Hackathon YAS Togo',
            'year' => '2026',
            'featured' => true,
            'cover' => 'todzi',
            'summary' => 'Carte temps réel des inondations de Lomé : signalement, SOS, itinéraire sécurisé, heatmap de risque.',
            'description' => "TODZI — « l'eau de pluie » en éwé — est une application mobile et web conçue pour le hackathon YAS Togo. Elle permet aux habitants de Lomé de signaler les zones inondées, d'alerter les secours, et de calculer un itinéraire qui évite l'eau.",
            'body' => [
                "Lomé est régulièrement paralysée pendant la saison des pluies. Les alertes officielles descendent de l'État vers les citoyens. TODZI fait l'inverse : une carte collaborative, alimentée par les habitants, utile à la circulation, aux comités de quartier et aux autorités.",
                "L'application tourne en PWA (React + Vite), avec une carte Leaflet, une file hors-ligne pensée pour les réseaux togolais, un SOS WhatsApp/SMS qui fonctionne même en 2G, et un score de risque explicable par quartier.",
            ],
            'stack' => ['React', 'Vite', 'Leaflet', 'Supabase', 'PWA'],
            'highlights' => [
                ['label' => 'Carte', 'value' => 'Leaflet temps réel'],
                ['label' => 'Réseau', 'value' => 'SOS même en 2G'],
                ['label' => 'Format', 'value' => 'PWA hors-ligne'],
            ],
            'links' => [],
            'private' => true,
        ],
        [
            'slug' => 'froid-du-centre',
            'title' => 'Froid du Centre',
            'kicker' => 'Produit métier',
            'year' => '2026',
            'featured' => true,
            'cover' => 'froid',
            'summary' => 'Application de gestion pour une entreprise de froid : factures, stock, tâches, rapports. Flutter et Spring Boot.',
            'description' => "Un outil interne pour Froid du Centre : facturation PDF, stock, tâches pour les apprentis, rapports mensuels et comptes multi-rôles. Client Flutter (Android, web, Windows), backend Spring Boot + MySQL.",
            'body' => [
                "Ce n'est pas un projet d'école. L'application est utilisée en interne : le patron crée les tâches, les apprentis les reçoivent, les factures sortent en PDF, le stock reste à jour.",
                "J'ai conçu l'architecture de bout en bout — modèle de données, API Java, application Flutter, notifications, sauvegardes — jusqu'au déploiement.",
            ],
            'stack' => ['Flutter', 'Spring Boot', 'MySQL', 'Firebase'],
            'highlights' => [
                ['label' => 'Usage', 'value' => 'Outil interne réel'],
                ['label' => 'Client', 'value' => 'Android / web / Windows'],
                ['label' => 'Cœur', 'value' => 'Factures · stock · tâches'],
            ],
            'links' => [],
            'private' => true,
        ],
        [
            'slug' => 'nba-analytics',
            'title' => 'NBA Analytics',
            'kicker' => 'AQX Data Bowl 3.0',
            'year' => '2026',
            'featured' => true,
            'cover' => 'nba',
            'summary' => 'Dashboard NBA : classements, stats joueurs, modèle Elo et métriques avancées. React + Vite.',
            'description' => "Dashboard interactif soumis au hackathon AQX Sports Analytics Data Bowl 3.0. Classements Est/Ouest calculés sur la saison réelle, stats des joueurs, et un modèle Elo backtesté sur 1 236 matchs.",
            'body' => [
                "Le dashboard repose sur des snapshots (balldontlie + SportsDataVerse) plutôt que sur un flux API trop limité. J'ai ajouté des métriques avancées — PER, TS%, USG% — et un modèle Elo à 66,7 % de précision sur le backtest.",
                "Le site est en ligne sur Vercel.",
            ],
            'stack' => ['React', 'Vite', 'Recharts'],
            'highlights' => [
                ['label' => 'Elo', 'value' => '66,7 % de précision'],
                ['label' => 'Backtest', 'value' => '1 236 matchs'],
                ['label' => 'Live', 'value' => 'Vercel'],
            ],
            'links' => [
                ['label' => 'Voir en ligne', 'url' => 'https://nba-analytics-dashboard.vercel.app'],
                ['label' => 'GitHub', 'url' => 'https://github.com/canis-lupu2006/nba-analytics-dashboard'],
            ],
            'private' => false,
        ],
        [
            'slug' => 'gestion-stock',
            'title' => 'Gestion de stock',
            'kicker' => 'Spring Boot',
            'year' => '2026',
            'featured' => false,
            'cover' => 'stock',
            'summary' => 'Système de stock pour le froid et la climatisation, avec génération de factures PDF.',
            'description' => "Application complète de gestion de stock : modélisation MySQL, couche repository, et export de factures professionnelles en PDF. Pensée pour les produits liés au froid et à la climatisation.",
            'body' => [
                "J'ai conçu le modèle relationnel, développé le backend Spring Boot, et intégré la génération / le téléchargement de factures PDF — le même fil que j'ai ensuite poussé plus loin dans Froid du Centre.",
            ],
            'stack' => ['Java', 'Spring Boot', 'MySQL'],
            'highlights' => [
                ['label' => 'Cœur', 'value' => 'Stock + factures PDF'],
                ['label' => 'Modèle', 'value' => 'MySQL relationnel'],
                ['label' => 'Suite', 'value' => 'Base de Froid du Centre'],
            ],
            'links' => [
                ['label' => 'GitHub', 'url' => 'https://github.com/canis-lupu2006/GESTION_STOCK'],
            ],
            'private' => false,
        ],
        [
            'slug' => 'jenkins-cicd',
            'title' => 'Pipeline CI/CD',
            'kicker' => 'Jenkins · Maven',
            'year' => '2026',
            'featured' => false,
            'cover' => 'jenkins',
            'summary' => 'Intégration et déploiement d\'un site de restauration : surveillance GitHub et builds Maven automatiques.',
            'description' => "Configuration d'un pipeline Jenkins sous Windows pour un site de restauration : dès qu'un commit arrive sur GitHub, le build Maven se lance tout seul.",
            'body' => [
                "Le but n'était pas juste de « faire du Jenkins ». C'était d'avoir une chaîne réelle — dépôt, build, déploiement — qui tient sans cliquer à la main.",
            ],
            'stack' => ['Jenkins', 'Maven', 'GitHub', 'JavaScript'],
            'highlights' => [
                ['label' => 'Trigger', 'value' => 'Commit GitHub'],
                ['label' => 'Build', 'value' => 'Maven automatique'],
                ['label' => 'Cible', 'value' => 'Site restauration'],
            ],
            'links' => [
                ['label' => 'GitHub', 'url' => 'https://github.com/canis-lupu2006/jenkins'],
            ],
            'private' => false,
        ],
        [
            'slug' => 'video-club',
            'title' => 'Vidéo club',
            'kicker' => 'MERISE / UML',
            'year' => '2025',
            'featured' => false,
            'cover' => 'video',
            'summary' => 'Gestion complète d\'un club vidéo : modèle MERISE/UML et règles métier via triggers MySQL.',
            'description' => "Système de gestion pour un club de location vidéo. La base est modélisée en MERISE/UML ; les règles de gestion passent par des triggers MySQL.",
            'body' => [
                "Un projet de conception autant que de code : bien poser les entités, les relations, et laisser la base garantir une partie des règles métier.",
            ],
            'stack' => ['MySQL', 'MERISE', 'UML'],
            'highlights' => [
                ['label' => 'Conception', 'value' => 'MERISE / UML'],
                ['label' => 'Règles', 'value' => 'Triggers MySQL'],
                ['label' => 'Domaine', 'value' => 'Location vidéo'],
            ],
            'links' => [],
            'private' => false,
        ],
        [
            'slug' => 'edusphere',
            'title' => 'Edusphere',
            'kicker' => 'Hackathon',
            'year' => '2026',
            'featured' => false,
            'cover' => 'edu',
            'summary' => 'Projet de hackathon autour de l\'éducation.',
            'description' => "Edusphere est un projet développé en hackathon, côté éducation. Une base pour explorer comment le numérique peut servir les étudiants et les écoles.",
            'body' => [
                "Développé dans le rythme d'un hackathon : cadrer vite, livrer quelque chose de démontrable, et garder une architecture lisible.",
            ],
            'stack' => ['Hackathon'],
            'highlights' => [
                ['label' => 'Cadre', 'value' => 'Hackathon'],
                ['label' => 'Sujet', 'value' => 'Éducation'],
                ['label' => 'Enjeu', 'value' => 'Livrer sous pression'],
            ],
            'links' => [
                ['label' => 'GitHub', 'url' => 'https://github.com/canis-lupu2006/Edusphere-'],
            ],
            'private' => false,
        ],
        [
            'slug' => 'chatbot-esgis',
            'title' => 'Chatbot ESGIS',
            'kicker' => 'Service campus',
            'year' => '2026',
            'featured' => false,
            'cover' => 'chat',
            'summary' => 'Chatbot pour répondre aux questions d\'un service de l\'école.',
            'description' => "Un chatbot conçu pour un service particulier de l'ESGIS : répondre aux questions fréquentes sans faire attendre quelqu'un derrière un bureau.",
            'body' => [
                "L'idée est simple : un canal unique, des réponses utiles, moins de va-et-vient pour les étudiants.",
            ],
            'stack' => ['Chatbot'],
            'highlights' => [
                ['label' => 'Lieu', 'value' => 'ESGIS'],
                ['label' => 'Usage', 'value' => 'Questions fréquentes'],
                ['label' => 'Effet', 'value' => 'Moins d’attente au bureau'],
            ],
            'links' => [
                ['label' => 'GitHub', 'url' => 'https://github.com/canis-lupu2006/chatbot-esgis'],
            ],
            'private' => false,
        ],
    ],
];
